### ISSUE TITLE
Add core recommended PHP extensions to site status

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#169]
The `Site Status` tab checks for the PHP JSON extension, but there are other recommended (or required) libraries we should also take note of, for example GD as a minimum for any image manipulation and so forth.

Let's extend the JSON check, and make it a core requirements check instead.

**Comment by knutsp** [comment]
Prefer one of the mysqli extensions over mysql extensions.
imagick is better than just GD, and used when available
mbstring is used (?), or should be recommended, only when site or user not en_US
gettext may be used in the future (5.0), only when site or user not en_US
Other extensions that WP might take advantage of? 

Since performance is an argument to upgrade from PHP 7.1 to 7.2, any extension that WP might use, when available, should be checked for.

**Comment by Clorith** [comment]
Let's use the hosting teams recommendations as the guideline to follow here https://make.wordpress.org/hosting/handbook/handbook/server-environment/
