### ISSUE TITLE
Remove copy-text indentation

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#176]
### Feature request/bug description

The copy-field has some extra indentations for the first line before the `WordPress` heading.

This should be removed.

### Screenshots
![image](https://user-images.githubusercontent.com/468735/43419335-ea7878b0-9440-11e8-9379-5d7e02be776b.png)

**Comment by jocastaneda** [comment]
This happens because of these two lines:
* https://github.com/WordPress/health-check/blob/master/src/pages/debug-data.php#L42
* https://github.com/WordPress/health-check/blob/master/src/pages/debug-data.php#L94

Removing the whitespace and using
```php
rows="10">`<?php
```
removes that. Super quick fix for somebody to pick up
