### ISSUE TITLE
Check plugin/theme update filters

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#23]
Check if filters are introduced that touch the update procedures for plugins or themes, we already check filters for core updates, so this is a natural enhancement to introduce.

**Comment by Clorith** [comment]
For a first iteration, just knowing if there's anything that may affect updates is ideal, providing a list might be something for the debug tab I would say.

**Comment by PeterBooker** [comment]
It looks like there are many ways plugin and theme updates can be blocked/tampered with, so here is a breakdown of what I have found (using plugins as an example, themes work almost identically):

Plugin updates are run through the functions `_maybe_update_plugins()` and `wp_update_plugins()`. The former checks the site transient `update_plugins` to see if 12 hours has passed since the last check and calls `wp_update_plugins()` if so. This means that you can prevent some update paths by using the filter `site_transient_update_plugins` to make it look like an update was performed recently, so that `_maybe_update_plugins()` never triggers an update.

The above functions are called directly, mainly through action hooks. Here are the ones I could find:

- add_action( 'load-plugins.php', 'wp_update_plugins' );
- add_action( 'load-update.php', 'wp_update_plugins' );
- add_action( 'load-update-core.php', 'wp_update_plugins' );
- add_action( 'wp_update_plugins', 'wp_update_plugins' );
- add_action( 'admin_init', '_maybe_update_plugins' );

Removing these is another way to stop plugin updates.

There is also a scheduled event which triggers updates, which can be disabled with `wp_clear_scheduled_hook( 'wp_update_plugins' )`.

Last, you can add a filter to `http_request_args` which lets you identify and then remove plugins from the HTTP request to wp.org looking for updated plugins. This would let you block one or more plugins from updating.

There are other options, like interfering with the actual plugin update- for example filtering `upgrader_pre_download` to prevent the download of the package, but this seems unlikely as it would be a terrible user experience (they could see an update, but not make it).

I propose that to begin with we check for the actions being removed and the scheduled event being removed, as anyone doing so would likely be attempting to block all updates. Looking past that we could filter `site_transient_update_plugins` and `http_request_args` early and late, and compare to see if they have been tampered with (e.g. some plugins removed, all plugins removed, etc).

What are your thoughts?

**Comment by Clorith** [comment]
Sounds like good first (and 2nd, 3rd etc) steps 👍
