### ISSUE TITLE
Check for old core files

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#259]
### Feature request

Like this plugin https://wordpress.org/plugins/old-core-files/

From the description:
> When core is being upgraded, usually some files are no longer used by WordPress, and they are set for removal.
> On some occasions, PHP has no permissions to delete these files, and they stay on the server. Old Core Files alerts you to remove old files before hackers attempt to exploit them for attacks.

This could be a great additional feature in our Tools section.

Or does the integrity check founds additional files like these?

**Comment by Clorith** [comment]
The integrity check doesn't look for old files, no, it only compares values between the files we get checksums for from WordPress.org

I agree, this would be a great tool to include, I'm torn between doing it as a site status (removing obsolete core files could be considered a security precaution for example), or a Tool because.. well, it's sort of tool-like.

Perhaps a Tool for now, with the intent of judging usefulness before potentially migrating it over to a site health indicator?

**Comment by Zodiac1978** [comment]
If this tool would be recognizing all files which are not part of WordPress this could add more complexity but also it would be more useful to detect malware.

Sometimes people add more folder/files in the root (for example the google search console verification file). This would produce many false positives. Maybe we should exclude the root folder or limit the check to just check for old core files.

The advantage if we check for all non core files is, a user can use the integrity scan and the old core files scan to know if there are non-wordpress files in the installation.

**Comment by Clorith** [comment]
I believe touching files outside of core is out scope, and is better left to security plugins that focus on that.
