### ISSUE TITLE
PHP notice when disabling certain plugin(s)

### ISSUE THREAD

**Issue by Viper007Bond** [WordPress/health-check#28]
If I have Health Check enabled and I deactivate [Query Monitor](https://wordpress.org/plugins/query-monitor/) (not sure why this specific plugin), the plugin page throws a PHP notice (I have high error reporting on).

> Notice: Undefined index: plugin in .../wp-content/plugins/health-check/health-check.php on line 232

Refreshing the page doesn't get rid of the error but reactivating Query Monitor makes the notice go away.

The only guess I have is that it adds a must-use `db.php` symlink to `wp-content`.

![firefox_2018-01-16_19-45-25](https://user-images.githubusercontent.com/406254/35024732-09ac1186-faf6-11e7-9a0d-492f1bf20fd2.png)

**Comment by Clorith** [comment]
Ahh yes, this is because the plugin data is surprisingly inconsistent at times, a fix for this was introduced in 4f9130c8b88e932d5268fe07c7057b8f961611c7, and will be out with the next version, you should be able to grab master off here if you'd be able to test and check if it solves it on your end?

**Comment by Viper007Bond** [comment]
Yep, that looks like it fixes it! 👍
