### ISSUE TITLE
Copy to clipboard - clarity

### ISSUE THREAD

**Issue by joedolson** [WordPress/health-check#287]
### Feature request/bug description

It's not clear to me on looking at the 'copy to clipboard' feature exactly *what* it would be copying. This is largely because I don't associate a rich accordion UI with something that I would copy and paste. 

Because of this, I think that the copy to clipboard should be integrated with a textarea that's visible at the time you're using the button: this serves to make it much more clear exactly what you're copying. 

Ideas:

- Add an accordion item that shows the plaintext version & copy to clipboard
- Have a button that instead says "show plaintext version" & offers option to copy to clipboard

The main key is giving people an opportunity to review what they're copying as a block prior to copying to clipboard, Dynamically displaying and removing shouldn't be a problem; there's no reason that should be considered significantly different from the existing accordion controls, unless I'm radically misunderstanding what you're describing. (Per https://wordpress.slack.com/archives/C02RP4X03/p1550943234153200)

**Comment by Clorith** [comment]
You are right, there's nothing preventing us from displaying it first (and it's shown it self to be a requirement for copy-features to work).

I did some reading up on this, to look into displaying it temporarily and then removing it afterwards, and I saw there were accessibility concerns with that (due to focus movement and loss and such), so we'll of course want to avoid that approach.

Having it display the box, then offer a copy button sounds like the best approach here, I'll mark it for design input as well since it'll introduce a new element to the page that they may have thoughts on.
