### ISSUE TITLE
Translations are lost after getting the English copy-paste-field

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#30]
One of our features includes a copy and paste field in English if your locale is something other than `en_US` (the default for WordPress) on the debug tab.

It appears our use of [`switch_to_locale()`](https://github.com/WordPress/health-check/blob/master/includes/class-health-check-debug-data.php#L14) and then restoration with [`restore_previous_locale()`](https://github.com/WordPress/health-check/blob/master/includes/class-health-check-debug-data.php#L665) makes us lose any translated version of strings in the original language if they hadn't already been fetched and in-memory.

**Comment by swissspidy** [comment]
Workaround:

After the line `$english_info = Health_Check_Debug_Data::debug_data( 'en_US' );` you can add this:

```php
if ( ! is_textdomain_loaded( 'health-check' ) && _get_path_to_translation( 'health-check' ) ) {
	load_textdomain( 'health-check', _get_path_to_translation( 'health-check' ) );
}
```

Also:

Instead of `version_compare( get_bloginfo( 'version' ), '4.7', '>=' )` i would just check if `switch_to_locale()` exists. Same in `Health_Check_Debug_Data`. Makes it a bit easier to read.

Plus, one should always use the return value of `switch_to_locale()`, e.g.  `$switched_locale = switch_to_locale( $locale );` and then `if ( $switched_locale ) { restore_previous_locale(); }`
