### ISSUE TITLE
Add a "can send email" check

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#35]
Let's make this plugin the best support plugin and add some features.

From time to time people blaming WordPress for not sending email. We could add an [check](https://de.wordpress.org/plugins/check-email/) for an easy and fast debugging of this feature.

**Comment by Clorith** [comment]
This one's a bit tricky, as the `wp_mail()` (and thus,subsequently, `mail()`) can still be working, even if emails don't arrive to one mailbox or another. This is because other factors may play in, emails are more likely to be blocked by spam filters, spf filters, blacklists and those are harder to detect.

Adding a "send test e-mail" button is a trivial matter, but adding features that are likely to provide false positive results just as often as not has me a little bit on the fence.

Creating a separate plugin just for this purpose, but one that does it _properly_ is definitely something that' sprung to mind more than once.

I'll outline my plans though, as I would love some feedback here, but it will have to be a separate plugin as it's too much to bundle with this one I fear just because of some of the prerequisites:

There needs to be a standalone mail server, without any kind of filtering enabled. A WordPress site sends an email to this mail server, which in turn checks SPF and DKIM of the sender. It also checks that the headers are correct, that the body matches what is expected (in case something filters outbound messages), and checks the sender reputation with blacklists.

Once all those tests are done, it stores the result for 24 hours, the WordPress site polls for results every so often until it gets a response that tests are completed. When tests are completed and fetched by the site, the results are deleted from the test service (the 24 hour limit is if the site for whatever reason stops checking, as we don't want to be sitting on a list of emails).

This would be a proper email check, my problem with the plugins out there that claim to do email testing is that they just trigger `wp_mail()` and then call it a day, that's not how emails work unfortunately.

---

I went on a bit there, but yes, we could add a simple `Send test e-mail`. We just need to make sure we're happy with something as simple as that which could be incorrectly giving an impression of emails not being sent when they are.

**Comment by mrxkon** [comment]
Since users are able to change the how wp_mail() works through plugins etc. A simple 'send mail' button somewhere and an input box for a custom e-mail address would suffice in my opinion and just explain to check if the mail actually arrives I guess.

I'm not sure that wp_mail() returns errors as well so they could be printed (?).

**Comment by Clorith** [comment]
Introduced in 0d09bcb3a6fdecc11d1bb755710f2b2de61e56e0
