### ISSUE TITLE
Your site could not complete a loopback request - live and local

### ISSUE THREAD

**Issue by dingo-d** [WordPress/health-check#357]
### Feature request/bug description

I'm getting `Your site could not complete a loopback request` on both live and local sites (docker and VVV).

```bash
Loopback requests are used to run scheduled events, and are also used by the built-in editors for themes and plugins to verify code stability.

The loopback request to your site failed, this means features relying on them are not currently working as expected.
Error: [] cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received
```

Not quite sure what's going on, I can update the site (live) and plugins just fine 🤷‍♂

**Comment by Clorith** [comment]
I'm not familiar enough with VVV to provide input on that, but for docker, you need to provide a reliable address that the containers can reach between each other in a local setup (see the [network setup Health Check uses for example](https://github.com/WordPress/health-check/blob/master/docker-compose.yml#L67-L70), which relies on you using `health-check.localhost` as the address for this exact purpose).

As for the error on a production site, there are two cases where I've seen that has been when the site has had firewall rules in place, or were blocking traffic in a way that made the host incapable of creating requests to it self. You can install plugins, run manual updates etc. just fine without this feature working, but automated updates, scheduled posts and similar rely on it if you use WordPress' built in cron solution.

The other case would be a plugin and/or theme conflict preventing some core functionality from behaving as intended, if you are running the plugin this can be checked by running Troubleshooting Mode and seeing if the problem is replicable then or not (if it's replicable, it's likely a host issue).

If you're looking for more help beyond that in identifying the reason, I would suggest making a support topic on the [WordPress.org forums](https://wordpress.org/support/).

**Comment by Clorith** [comment]
As this issue has become stale, and I believe the previous response covers the reason for the notice shown, I'm closing the ticket at this time.
