### ISSUE TITLE
Consider splitting the plugin into a legacy and modern edition

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#365]
This is more a discussion point, but one that would help move things forward.

Currently the plugin supports WordPress 4.0 and onwards. As seen in various tickets, this is beneficial for users looking to upgrade from older version, but does limit us a fair bit in relation to improvements ahead of, and along with, WordPress core.

Would it make sense to fork the plugin, essentially making `Legacy Health Check` with the tools as they are now, that only receives bugfixes and security enhancements?

This would allow the main plugin to much more closely couple with core, remove backwards compatibility code, and basically make it easier to maintain with regards to porting code to and from core.

This of course has both pros and cons, and I want to hear the wider thoughts on it, and not just the voices in my head :)

**Comment by joyously** [comment]
Actually, I wondered about this, because of a forum topic. I was going to recommend Health Check, but didn't know if it had the part that moved to core, so I couldn't tell if it would work on the older WP.
I think it would be nice to have only one to recommend, regardless of WP version. But I can see how that would be high-maintenance. 
On the other hand, if all the code that is currently in core is moved to a file, that file could be `require`d according to WP version.

**Comment by joyously** [comment]
If there are two plugins, a user can install both at the same time. Would there be PHP name clashes with that?

**Comment by joyously** [comment]
I'm thinking that Health Check should remain the same, and any further explorations should be done in a new Beta plugin with "Site Health" in the name.

**Comment by Clorith** [comment]
Closing this as the direction taken is to show a note to legacy users that their versions are too old for certain features.
