### ISSUE TITLE
site broken

### ISSUE THREAD

**Issue by cassiomurilo** [WordPress/health-check#381]
I active this plugin and website broken. Not show error, access wp-admin page.

I remove the file health-check-troubleshooting-mode.php, but not resolved.

**Comment by Clorith** [comment]
Hi there,

It sounds like you've encountered some issues with the plugin it self, would you be so kind as to open a support topic on our forums (https://wordpress.org/support/plugin/health-check/), and if it does turn out to be a bug, we'll create a ticket for it with the appropriate details.

Since this is an issue tracker for bugs and enhancements, I'm going to close this support request, but I do encourage you to make that topic :)

**Comment by cassiomurilo** [comment]
We managed to go back to the site commenting a woocommerce code. Thanks. 

it took us a while to find out, after removing all plugins we managed to reach this code that is personalized. But in the end it was worth it.
