### ISSUE TITLE
Alpha/Beta versions and WP_DEBUG

### ISSUE THREAD

**Issue by javiercasares** [WordPress/health-check#387]
_This is just a suggestion. I did look at issues and did not find anything about._

I have a dev and beta installation for testing purposes and also have the WP_DEBUG enabled, so I can test... but the Site health always tells me that is a "critical" problem to have this.

Should we change from Critical to Recommendation the "Your site displays errors" when there is an alpha or beta version?

**Comment by Clorith** [comment]
The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating to these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org/).

Noting that the check for debug logging has had some logic changes, and only considers `define( 'WP_DEBUG_LOG', true );` as a critical issue, and other means of enabling it with custom paths as a recommendation instead, since core can't validate the public availability of the files.
