### ISSUE TITLE
Wrong Language on swedish site language and english user profile language

### ISSUE THREAD

**Issue by ipajen** [WordPress/health-check#448]
### Feature request/bug description

WordPress: 6.2
PHP: 8.2.3
Server: LiteSpeed
Database: mysqli (Server: 10.4.28-MariaDB / Client: mysqlnd 8.2.3)
Browser: Edge 111.0.1661.62 (Windows 10/11)
Theme: GeneratePress 3.3.0
Health Check & Troubleshooting 1.6.0

Got a issue with languages in Health check

Site Language = English US and User Profile Language = English
Status, Info, Troubleshooting, Tools

Site Language = English US and User Profile Language = Swedish
Status, Info, Felsökning, Verktyg

Site Language = Swedish and User Profile Language = English US
Status, Info, Felsökning, Verktyg

Site Language = Swedish and User Profile Language = Swedish
Status, Info, Felsökning, Verktyg

When site language are Swedish and User Profile Language are English US the wrong language is shown in the Troubleshooting, Tools?

Site Language = English US and User Profile Language = Swedish
The headers are translated but not the text. See pictures

Site Language = Swedish and User Profile Language = Swedish
The headers are translated and text. See pictures

### Screenshots

Is this a visual related ticket? If so, please include one or more screenshots to help us better understand what is happening.

![Sitelanguage_US_and_Userlanguage_SE](https://user-images.githubusercontent.com/116973963/229871397-fe849432-8c56-45d3-ae7e-86418d061ff5.JPG)
![Sitelanguage_SE_and_Userlanguage_SE](https://user-images.githubusercontent.com/116973963/229871391-0c87b371-6a51-47e6-9ab7-d8ba84ec9659.JPG)

**Comment by ipajen** [comment]
![IMG_4296](https://user-images.githubusercontent.com/116973963/230351181-35f773b4-0191-4aa8-8c72-3da0ad718a05.jpeg)
Added picture where translation is showing up incorrectly under plugins - troubleshooting

**Comment by Zodiac1978** [comment]
Maybe @swissspidy can help here?

**Comment by swissspidy** [comment]
From what I can see at a glance is that the way the code is loaded in the plugin causes the just-in-time translation logic in WP to trigger before the current user locale is known.

This is because the main plugin file loads a bunch of classes which get immediately instantiated before `plugins_loaded`, and these classes call `__()`:

https://github.com/WordPress/health-check/blob/1e0b6f51d2cada60fbc58c10db94d1688af2bb8c/health-check.php#L66-L73

https://github.com/WordPress/health-check/blob/1e0b6f51d2cada60fbc58c10db94d1688af2bb8c/HealthCheck/Tools/class-health-check-files-integrity.php#L20-L21

https://github.com/WordPress/health-check/blob/1e0b6f51d2cada60fbc58c10db94d1688af2bb8c/HealthCheck/Tools/class-health-check-files-integrity.php#L297

Doing all the main plugin initialization only on `plugins_loaded` would solve this.

----

See also https://core.trac.wordpress.org/ticket/58546
