### ISSUE TITLE
Your site is set to log errors to a potentially public file

### ISSUE THREAD

**Issue by ddur** [WordPress/health-check#449]
### Feature request/bug description

How about to check if debug.log is really accessible?
In example, try to access it via curl and site URL.
My debug.log is in wp-content/.debug/.debug.log

Thanks.

**Comment by Clorith** [comment]
Hiya, and thank you for the feature suggestion. The Site Health Check is a feature built into WordPress core at this time, so any feature requests for it should be reported via https://core.trac.wordpress.org/

That said, the reason it is not trying to check the file is that knowing the path to the file is hard/impossible. There may be other paths to the file than just WordPress' domain, file and directory permissions may differ based on server configurations for each site, and identifying the path could be incorrect (what if the path is outside of WordPress' directory, but symlinked elsewhere for example).
Due to the high level of unknowns, using the language of "potential" means the user is made aware that they need to be aware of this them self.

I'm going to close the ticket here on GitHub for now, since this is a core test, but if something pops up that means it should be handled in the plugin, I am of course more than happy for it to be re-opened at such a time :)

**Comment by ddur** [comment]
Thanks @Clorith
