### ISSUE TITLE
Try to get whitelisted from PHP Compatibility Checker plugin

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#53]
Because of this:

> FILE: /wp-content/plugins/health-check/pages/health-check.php
> --------------------------------------------------------------------------------------------------
> FOUND 2 ERRORS AFFECTING 2 LINES
> --------------------------------------------------------------------------------------------------
>   24 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
>  212 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
> ----------------------------------------------------------------------------------------------------
> 
> FILE: /wp-content/plugins/health-check/includes/class-health-check-debug-data.php
> --------------------------------------------------------------------------------------------------
> FOUND 2 ERRORS AFFECTING 2 LINES
> ----------------------------------------------------------------------------------------------------
>  432 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
>  441 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
> ----------------------------------------------------------------------------------------------------

**Comment by mrxkon** [comment]
I am too running Health Check with phpcs on both Compatibility + Coding Standards.

The second error that you mention is the `db_version()`, the last issue I created as well and closed 2 days ago ( https://github.com/WordPress/health-check/issues/47 ) as I was trying to make everything error - free. This is something that you can find on core also ( https://developer.wordpress.org/reference/classes/wpdb/db_version/ ).

If there's a decision to drop support for 5.5 back it can be converted to mysqli_ only. Until then that's an error that has to be ignored manually I guess.

If @Clorith thinks that we can make a proposal on core to alter that function a bit and return the full string instead of just numbers, maybe by passing an $arg, Health Check could use the core function then instead as well and become 'error free' :)

**Comment by Clorith** [comment]
I'm guessing you are testing using https://wordpress.org/plugins/php-compatibility-checker/, @Zodiac1978 ?

It's essentially just PHPCS being ran, but they're not accepting our PHPCS validation comments, so yes, we'll have to request a whitelist.

Whitelist is requested at https://github.com/wpengine/phpcompat/issues/179

**Comment by Clorith** [comment]
Going to close this on our end, there's nothing we can do except wait.

**Comment by Zodiac1978** [comment]
It is fine closing this here. Hopefully this is fixed in a later version of the plugin. No need to have two issues open.
