### ISSUE TITLE
php upgrade copy

### ISSUE THREAD

**Issue by futtta** [WordPress/health-check#54]
On the "health check" tab, as first entry the PHP-version is shown (7.0.x in my case) and reads
> For performance and security reasons, we strongly recommend running PHP version 7.2 or higher.

Given
* PHP 7.2 is the highest version available so there is no "or higher"
* PHP 7.2 is barely 3 months old so one might prefer to stick with 7.0 or 7.1
* PHP-versions often come as OS packages, 7.2 is probably not widely available that way 
* there are no security reasons why 7.2 would be better then 7.0 (or even 5.6)

I would propose the copy to be a tad more "permissive". This one would make more sense IMHO;

> For performance and security reasons, we strongly recommend running PHP version 7.0 or higher.

frank

**Comment by Clorith** [comment]
This one's a bit special, to call it that, although I definitely understand what you're saying.

The wording for PHP 7.2 is because this is the version recommended by WordPress, I'm using the "or higher" addition because the plugin may not always be 100% up to date with what the most recent version of PHP is, so this gives us that permissive bit you mentioned, (and also allows just 7.2 to cover any minor versions as well, as in my mind I would expect that to mean 7.2.0 when something is omitted).

I am definitely open to recommendations on the PHP strings though, as they're a tricky one, so long as considerations for what the overall WordPress project says is taken into account as well, that's really what spurred the strings as they are right now, more or less.

We could probably omit the "security" part of that string for versions that are still officially supported by PHP, I agree with you there.

So, what then, about 
> For performance reasons, we recommend running PHP 7.2 or higher.

This removes security as a reasoning for supported versions, it also removes "strongly recommend", as this feels like a more pressured "do it", and that's not needed for this scenario. It does retain 7.2, and lastly retains 7.2 as the recommended version by core.

**Comment by futtta** [comment]
Better ... What about:

> For best performance we recommend using PHP 7.2 or higher.

**Comment by Clorith** [comment]
I quite like that, yes!

**Comment by pedro-mendonca** [comment]
Will it make sense to make the db upgrade copy the same?
https://github.com/WordPress/health-check/blob/master/src/pages/health-check.php#L143

> For best performance we recommend using %1$s version %2$s or higher.
