### ISSUE TITLE
Show more information when sending test mail.

### ISSUE THREAD

**Issue by mrxkon** [WordPress/health-check#66]
https://github.com/WordPress/health-check/blob/f061ea1a7f10327c388146d16eeec61b518dc218/src/includes/class-health-check-mail-check.php#L28-L29

From slack : `mods pointed that it will be nice to have site name and/or address in message body`

Shall we re-write this to :
`subj: Health Check: {$siteaddress} Test Message`
`body: This message was sent as a test from {$sitename} - {$siteaddress} - Health Check.`

Any extra information that we might want to add in there as well since it's going to be populated maybe?

**Comment by tobifjellner** [comment]
What  about:
subject: Health Check – Test Message from {$siteaddress}
body: Hi <br />This test message was sent by the Healt Check plugin from {$sitename} – ({$siteaddress}) on. {date} at {time}. Since you’re reading this, it obviously works. 
Additional message from admin: {escaped/cleaned additional message from send form}

**Comment by mrxkon** [comment]
#68 is updated with the current master and ready for merge as well :]
