### ISSUE TITLE
Should we add a link to latest releases of PHP?

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/health-check#77]
In Health Check, we tell the user which PHP version they are using (and suggest that they should use 7.2).
That's all good.
I was thinking whether we also just should add a link to more detailed information about the latest _releases_ (rather than just _version_):
For instance like this:
To check if you’re using the latest release of your PHP version, visit http://php.net/downloads.php about corrected bugs and security issues.

**Comment by Clorith** [comment]
I don't think that will help much, I think it's better to send them to the Upgrade PHP page on WordPress.org, as the upgrade paths are different or various hosts, hosts may not have vetted the latest builds etc. The page on .org may eventually have tools for this, so it makes more sense to just send them there.

Thoughts?

**Comment by tobifjellner** [comment]
In that case it's probably better to say nothing at all about releases, since that's a can of worms.
Even if your web host control panel offers you to choose from several PHP versions (5.6, 7.0, 7.1, etc.) it certainly won't give you any tools to speed up the roll-out of new PHP security releases.
If someone runs their own server, then this might help them, but the really should make sure to be on the right mailing lists for notifications anyway...

**Comment by mrxkon** [comment]
Imho we could just wait for ServeHappy to be finalized and running as maybe that would be even more fitting since there will be an extra notification inside WP and the extra full informational page ^_^.

Let's not forget that HC isn't used only by Admins but from non-techy people as well and a link straight to php.net might mess with their head more as they wouldn't understand pretty much anything from in there :D 

Informing people that there's a better version is ok, but over-informing them with things that they won't understand would make them uncomfortable in my opinion. So the simpler the message the better ( that actual links to a helpful page to read more about what that is ).

**Comment by Clorith** [comment]
Aye, the introduction of this in HC is more of a "concept" than anything else i guess we could say, as ServeHappy will have a much better approach to it, we're just sticking to the basics.

**Comment by Clorith** [comment]
Going to close out this issue, we currently link to the Upgrade PHP page on WordPress.org, and for now that seems sufficient.
